// <auto-generated />
using System;
using GeometricFigure.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GeometricFigure.Migrations
{
    [DbContext(typeof(GeometricFigureContext))]
    [Migration("20210119130508_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("GeometricFigure.Entities.Figure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Perimeter")
                        .HasColumnType("REAL");

                    b.Property<double?>("Radius")
                        .HasColumnType("REAL");

                    b.Property<double?>("SideA")
                        .HasColumnType("REAL");

                    b.Property<double?>("SideB")
                        .HasColumnType("REAL");

                    b.Property<double?>("SideС")
                        .HasColumnType("REAL");

                    b.Property<double?>("Square")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Figure");
                });
#pragma warning restore 612, 618
        }
    }
}
